- gulpfile.js
- src/dataviz/dataviz.js
- src/dataviz/lib/chartOptions.js
- test/examples/dataviz/index.html
This PR also includes a fix to our build process that was snagging browserify from producing new files.. fun!
> Fix how #chartOptions applies properties, fixes #215

- src/dataviz/lib/attributes.js
Insert any options you set to false in the configuration of the graph.
> BugFix ChartOptions

- docs/query.md
I was just trying this out and it seems these two are inverted in the docs. The new fix works as intended.
> Order of callback parameters are inverted.

- docs/dataviz.md
- package.json
- src/dataviz/adapters/c3.js
- src/dataviz/adapters/google.js
- src/dataviz/dataviz.js
- src/dataviz/index.js
- src/dataviz/lib/labels.js
- src/dataviz/lib/parseRawData.js
- src/dataviz/lib/stacked.js
- test/examples/dataviz/c3/index.html
- test/examples/dataviz/index.html
- test/unit/modules/dataviz/dataviz-spec.js
Fixes #234, less cryptic message for empty results
> Various fixes for Dataviz edge cases

- docs/visualization.md
Based on comments in this ticket in Groove: https://keen-io.groovehq.com/groove_client/mailboxes/4308/filters/51672/tickets/5120277
> Changed LabelMapping to labels in funnel

- README.md
- docs/visualization.md
This is technically a DOM node that's required, not a selector.
> Change "selector" to "node"

- docs/query.md
review please :sunglasses: [ci skip]
> Update JS docs [query.md] to include query caching

- README.md
located right under "querying events"
> Adding query caching how-to [ci skip]

- README.md
- docs/visualization.md
* improve documentation : make auto-refresh examples consistent with example in docs/dataviz/README.md
> improve documentation

- src/dataviz/lib/parseRawData.js
- test/unit/index.js
- test/unit/modules/dataviz/dataviz-spec.js
- test/unit/modules/dataviz/parseRawData-spec.js
This PR adds unit tests for the code that parses responses from the Keen API 
* run `gulp with-tests`
There are no related issues, however, this part of the code is a critical part of keen-js and explorer and should have tests in case of bugs, which have come up before. This part of the code will also likely be refactored, so it should have test coverage for each of the scenarios.
> Tests for 'parseRawData'

- docs/visualization.md
Added jsfiddles link to Visualization.md
- Exposing useful examples for users
- It has some Google Charts related examples and was hidden away with Chart.js and C3.js docs
N/A
No
N/A
> Added fiddles link to visualizations doc

- src/dataviz/adapters/chartjs.js
- test/examples/dataviz/chartjs/index.html
Displays a message in the chart if there's no data.
Open `test/examples/dataviz/chartjs/index.html`
See https://app.intercom.io/a/apps/5eadb8aff7474e2d465c4fc13242935d5b4e1405/inbox/conversation/1145975440 and http://jsfiddle.net/Nopik/goq4ga1a/1/
> display message when result is empty

- README.md
- src/core/helpers/superagent-request-types.js
- src/core/query.js
- src/core/request.js
- src/core/saved-queries.js
- src/core/utils/sendQuery.js
- src/core/utils/sendSavedQuery.js
- src/keen-query.js
- src/keen.js
- src/server/index.js
- test/unit/helpers/mockServerRequests.js
- test/unit/modules/core/query-spec.js
- test/unit/modules/core/request/server-spec.js
- test/unit/modules/core/saved-queries-spec.js
- test/unit/server.js
* Adding support for saved queries.
* Refactoring `utils/sendQuery.js`
> Saved queries support

- docs/scoped-keys.md
> semicolon to coma.

- docs/README.md
- docs/dataviz/c3.md
- docs/dataviz/chartjs.md
- docs/installation.md
> Update version in documentation

- README.md
- docs/installation.md
https://github.com/keen/keen-js/issues/355#issuecomment-156231882
> Add note to README about re-versioning

- CONTRIBUTING.md
hey folks. I'm working on an updated version of our contributing doc that I'm planning on using for all of our SDK's and potentially other OSS projects. I'm taking a crack at the JS one first and would love feedback.
> update the contributing guide to be more community friendly

- CONTRIBUTING.md
- README.md
Adds the Code of Conduct to the CONTRIBUTING.md file as well as include a link to the page on the README.md
Read over it. I want to make sure everything sounds clear.
> Add Code of Conduct

- README.md
> Add license badge and report

- README.md
- package-lock.json
- package.json
to make things much more clear during the installation
> readme node server side example
